name: Deploy Documentation
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: npm

      - name: Upgrade npm
        run: |
          # Install latest npm
          npm install -g npm@latest

      - name: Build website
        run: |
          npm ci --legacy-peer-deps
          npm run build

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        if: success()
        with:
          local-dir: ./build/
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true
